---
# DOC: https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#install-multiple-collections-with-a-requirements-file
# collections:
#   - ansible.netcommon
#   - ansible.utils
