---
- name: Return role final result in suitable way and format
  ansible.builtin.debug:
    msg: "{{ role_result }}"
  when:
    - role_result is defined

- name: Role execution final stats
  ansible.builtin.set_stats:
  per_host: true
  data:
    role_result: "{{ role_result }}"
