group1:
  hosts:
    host1:
      var1: value1
      var2: value2
    host3:
      var1: value1
      var2: value2
group2:
  hosts:
    host2:
      var1: value1
      var2: value2
  vars:
    var4: value4
group3:
  children:
    group1:
    group2:
  vars:
    var3: value3
