
---
#
# NOTES: just a playbook template. The fie should be renamed from verb_noun.yml to something meaningfull like: set_server.yml, get_info.yml, etc.
#
- name: Playbook name and/or brief description
  hosts: all
  connection: local
  gather_facts: false
  any_errors_fatal: true
  collections:
    - collectionA
    - collectionB

  pre_tasks:

    - name: Set global fact for base dir
      set_fact:
        play_dir: "{{ playbook_dir | dirname }}"

    - name: Assert variables
      assert:
        that: "{{ item }} is defined"
        msg: "{{ item }} is not defined"
      loop:
        - env
        - mandatoryvariable1
        - mnadatoryvariable2

    - name: Include pre-tasks
      include_tasks: "{{ play_dir }}/pretasks.yml"

  tasks:

    - name: Task name and/or brief description
      include_role:

        name: first_role

      vars:
        action: action1

